"""add file_modified_at to submission

Revision ID: 175f2d31d173
Revises: dd4b2bce9163
Create Date: 2026-04-28 20:09:59.686134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175f2d31d173'
down_revision = '20260428_increase_auditlog_ip_useragent_length'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_modified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('file_modified_at')

    # ### end Alembic commands ###
