"""Add file_content to submissions

Revision ID: 26309331d64c
Revises: add_rubric_evaluation_caching
Create Date: 2026-05-05 01:22:19.589657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26309331d64c'
down_revision = 'add_rubric_evaluation_caching'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_content', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('file_content')

    # ### end Alembic commands ###
